language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - extra-android-m2repository
    - build-tools-25.0.0
    - android-25
    
notifications:
  email: false
  
script: gradle build
