language: android

jdk:
 - oraclejdk7
 - oraclejdk8

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support

script:
  - ./gradlew clean check -Dpre-dex=false

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
