language: android

jdk:
 - oraclejdk7

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support

script:
  ./gradlew clean

notifications:
  email: false

sudo: false

./gradlew build connectedCheck
